[package]
name = "chip-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
bincode = "1.3.3"
wasmtime = "0.35.1"
wgpu = "0.12.0"
rustc-hash = "1.1.0"
naga = "0.8.5"